### ISSUE TITLE
No such var: ig-utils/last-modified - kit-sql-conman 1.0.9

### ISSUE THREAD

**Issue by Bost** [kit-clj/kit#123]
1.0.8 works fine. 1.0.9 produces:

```
$ clj -M:dev:nrepl
Exception in thread "main" Syntax error compiling at (kit/edge/db/sql/conman.clj:26:14).
	at clojure.lang.Compiler.analyze(Compiler.java:6825)
	at clojure.lang.Compiler.analyze(Compiler.java:6762)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3900)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7126)
	at clojure.lang.Compiler.analyze(Compiler.java:6806)
	at clojure.lang.Compiler.analyze(Compiler.java:6762)
	at clojure.lang.Compiler$MapExpr.parse(Compiler.java:3116)
	at clojure.lang.Compiler.analyze(Compiler.java:6814)
	at clojure.lang.Compiler.analyze(Compiler.java:6762)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6137)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6453)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7124)
	at clojure.lang.Compiler.analyze(Compiler.java:6806)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7112)
	at clojure.lang.Compiler.analyze(Compiler.java:6806)
	at clojure.lang.Compiler.analyze(Compiler.java:6762)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6137)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6453)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7124)
	at clojure.lang.Compiler.analyze(Compiler.java:6806)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7112)
	at clojure.lang.Compiler.analyze(Compiler.java:6806)
	at clojure.lang.Compiler.analyze(Compiler.java:6762)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6137)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5479)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4041)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7122)
	at clojure.lang.Compiler.analyze(Compiler.java:6806)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7112)
	at clojure.lang.Compiler.analyze(Compiler.java:6806)
	at clojure.lang.Compiler.analyze(Compiler.java:6762)
	at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:1020)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7124)
	at clojure.lang.Compiler.analyze(Compiler.java:6806)
	at clojure.lang.Compiler.analyze(Compiler.java:6762)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6137)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5479)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4041)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7122)
	at clojure.lang.Compiler.analyze(Compiler.java:6806)
	at clojure.lang.Compiler.eval(Compiler.java:7191)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6908.invoke(core.clj:6161)
	at clojure.core$load.invokeStatic(core.clj:6160)
	at clojure.core$load.doInvoke(core.clj:6144)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5933)
	at clojure.core$load_one.invoke(core.clj:5928)
	at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
	at clojure.core$load_lib.invokeStatic(core.clj:5974)
	at clojure.core$load_lib.doInvoke(core.clj:5953)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6016)
	at clojure.core$load_libs.doInvoke(core.clj:6000)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6038)
	at clojure.core$require.doInvoke(core.clj:6038)
	at clojure.lang.RestFn.invoke(RestFn.java:805)
	at fdk.cmap.core$eval12772$loading__6789__auto____12773.invoke(core.clj:1)
	at fdk.cmap.core$eval12772.invokeStatic(core.clj:1)
	at fdk.cmap.core$eval12772.invoke(core.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7194)
	at clojure.lang.Compiler.eval(Compiler.java:7183)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6908.invoke(core.clj:6161)
	at clojure.core$load.invokeStatic(core.clj:6160)
	at clojure.core$load.doInvoke(core.clj:6144)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5933)
	at clojure.core$load_one.invoke(core.clj:5928)
	at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
	at clojure.core$load_lib.invokeStatic(core.clj:5974)
	at clojure.core$load_lib.doInvoke(core.clj:5953)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:6016)
	at clojure.core$load_libs.doInvoke(core.clj:6000)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:6038)
	at clojure.core$require.doInvoke(core.clj:6038)
	at clojure.lang.RestFn.invoke(RestFn.java:930)
	at user$eval140$loading__6789__auto____141.invoke(user.clj:1)
	at user$eval140.invokeStatic(user.clj:1)
	at user$eval140.invoke(user.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7194)
	at clojure.lang.Compiler.eval(Compiler.java:7183)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:368)
	at clojure.lang.RT.maybeLoadResourceScript(RT.java:364)
	at clojure.lang.RT.doInit(RT.java:486)
	at clojure.lang.RT.init(RT.java:467)
	at clojure.main.main(main.java:38)
Caused by: java.lang.RuntimeException: No such var: ig-utils/last-modified
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:7405)
	at clojure.lang.Compiler.resolve(Compiler.java:7375)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7336)
	at clojure.lang.Compiler.analyze(Compiler.java:6785)
```

**Comment by gerdint** [comment]
Probably need to bump io.github.kit-clj/kit-core dep to 1.0.5?

**Comment by Bost** [comment]
I did that more than 3 months ago:

```bash
git log -S"io.github.kit-clj/kit-core {:mvn/version \"1.0.5\"}"
commit 23b72bf5a04acce7c0ba835e9ccbe58fb3668cc1
Author: Rostislav Svoboda <Rostislav.Svoboda@gmail.com>
Date:   Sat Sep 16 14:07:58 2023 +0200

    npm update, clojure -M:outdated --upgrade
```

See https://github.com/FdK-Stuttgart/Associations/commit/23b72bf5a04acce7c0ba835e9ccbe58fb3668cc1

**Comment by gerdint** [comment]
Ah, sorry, didn't check properly. The function conman is looking for was introduced by a recent PR (https://github.com/kit-clj/kit/pull/122/files). Seems like the kit-core lib version was not increased and hence the conman kit-core dep version unchanged. I was under the impression that @yogthos would handle that?

**Comment by yogthos** [comment]
Ah my bad, I forgot to push up kit-core 1.0.6 to Clojars. Should be fixed now.

**Comment by Bost** [comment]
It works now. Thanks for the fix.
