### ISSUE TITLE
Generated test fixture causes `RejectedExecutionException` when running tests in REPL

### ISSUE THREAD

**Issue by positron** [kit-clj/kit#147]
This is from a kit project started a couple months ago.
- clojure `1.12.0-rc1`
- kit-core `1.0.7`

I’m using the fixture kit generated in `apple.bgp-ctrl.test-utils` like this:

```
(use-fixtures :once (utils/system-fixture))
```

Then I have a single test that calls the `/api/health` endpoint.

When I run tests in the REPL the first succeeds, but then everything is broken and I have to actually kill the process because any attempt to interact with it via the REPL I get a `RejectedExecutionException` stack trace like the one I included at the bottom of this issue.

I traced the problem to `stop-app` in `my.app.core`. It calls `(shutdown-agents)`. If I comment out the agent shutdown I can start and stop the system as many times as I want.

Am I doing something wrong? It seems like this fixture or the start/stop code is broken unless you only use the fixture once per JVM boot.

-----------------
```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@696698fb[Not completed, task = clojure.core$binding_conveyor_fn$fn__5840@3e3728e1] rejected from java.util.concurrent.ThreadPoolExecutor@14e5df29[Shutting down, pool size = 3, active threads = 3, queued tasks = 0, completed tasks = 18]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
        at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)                                
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)                                          
        at clojure.core$future_call.invokeStatic(core.clj:7120)                                                                                                                       
        at clojure.core$future_call.invoke(core.clj:7110)                                                                                                                             
        at nrepl.server$handle.invokeStatic(server.clj:43)                                                                                                                            
        at nrepl.server$handle.invoke(server.clj:38)                                                                                                                                  
        at nrepl.server$accept_connection$fn__47222.invoke(server.clj:81)
        at clojure.core$binding_conveyor_fn$fn__5840.invoke(core.clj:2047)                                                                                                            
        at clojure.lang.AFn.call(AFn.java:18) 
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)                                                                                                         
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)                                                                                  
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by positron** [comment]
A possible fix is to move `(shutdown-agents)` to a separate hook only called via `.addShutdownHook` here:

https://github.com/kit-clj/kit/blob/dd70b82ca7dda2bfef48415c18f0e300c437565d/libs/deps-template/resources/io/github/kit_clj/kit/src/clj/core.clj#L51

Or are there cases where you'd want to shut down the clojure agents but keep using this JVM runtime?

**Comment by yogthos** [comment]
I think that's a reasonable default, and if it's needed to call `shutdown-agent` then it's always possible for the people to just add that call where they want.

**Comment by yogthos** [comment]
So you're thinking of just doing the following right?

```clojure
(defn stop-app []
  ((or (:stop defaults) (fn [])))
  (some-> (deref system) (ig/halt!)))

(defn start-app [& [params]]
  ((or (:start params) (:start defaults) (fn [])))
  (->> (config/system-config (or (:opts params) (:opts defaults) {}))
       (ig/expand)
       (ig/init)
       (reset! system))
  (.addShutdownHook (Runtime/getRuntime) (Thread. stop-app))
  (.addShutdownHook (Runtime/getRuntime) (shutdown-agents)))
```

And then `stop-app` won't be shutting down the agents which would make it REPL friendly.

**Comment by positron** [comment]
Any better way than to make some atom at the top to store if the shutdown hooks have been added or not? Doesn't look like it.

Last line needs to be `(Thread. shutdown-agents)` fyi.

**Comment by yogthos** [comment]
@positron ok, pushed up a new template with the fix, let me know if everything looks good on your end

**Comment by positron** [comment]
👍  LGTM, that is the code I'm using in my app now.

**Comment by positron** [comment]
Ok, sorry to re-open this. Through use I have found a bug in the code we decided on. The JVM does not guarantee the order in which the shutdown hooks will run, so there is a race condition if your `ig/halt` methods use anything shut down by `shutdown-agents`.

In my case I was using `(pmap disconnect-some-stuff stuff)` for one of my components, and the built in threadpool shut down, resulting in RejectedExecutionExceptions.

This happened in prod, not just tests as the title of the issue suggests. Here is my fix, combine the two things in to one shutdown hook that runs both sequentially:

```
(.addShutdownHook (Runtime/getRuntime) (Thread. (fn [] (stop-app) (shutdown-agents))))
```

**Comment by yogthos** [comment]
I added a PR for this, if this looks good I can push out a new version with the fix https://github.com/kit-clj/kit/pull/158/files

**Comment by yogthos** [comment]
new version is up
