### ISSUE TITLE
Exception when adding postgresql query result w/ timestamp to session state

### ISSUE THREAD

**Issue by jpe90** [kit-clj/kit#36]
When I try to query a [record](https://github.com/jpe90/kit-bug-demo/blob/ed1407e89b9d81ebfb49b4ac30e41fba6df337d7/src/clj/jpe/kit_bug_demo/web/routes/pages.clj#L20) that contains a [timestamp](https://github.com/jpe90/kit-bug-demo/blob/ed1407e89b9d81ebfb49b4ac30e41fba6df337d7/resources/migrations/20220302151247-add-users-table.up.sql#L7) from a postgres database and [assoc it to the session](https://github.com/jpe90/kit-bug-demo/blob/ed1407e89b9d81ebfb49b4ac30e41fba6df337d7/src/clj/jpe/kit_bug_demo/web/routes/pages.clj#L34), I'm getting an error that I couldn't make sense of (see below). If I dissoc the timestamp field before adding it to the session, or if I use sqlite, I don't get the error.

A minimal reproduction is available here: https://github.com/jpe90/kit-bug-demo. Accessing the root route at localhost:3000 will cause the app to try to add the user to the session and throw the following exception:

```
2022-03-02 14:47:52,448 [XNIO-1 task-1] ERROR io.undertow.request - UT005071: Undertow request failed HttpServerExchange{ POST /}
java.lang.AssertionError: Assert failed: (= x (deserialize % options))
	at ring.middleware.session.cookie$serialize.invokeStatic(cookie.clj:77)
	at ring.middleware.session.cookie$serialize.invoke(cookie.clj:77)
	at ring.middleware.session.cookie$seal.invokeStatic(cookie.clj:84)
	at ring.middleware.session.cookie$seal.invoke(cookie.clj:81)
	at ring.middleware.session.cookie.CookieStore.write_session(cookie.clj:100)
	at ring.middleware.session$bare_session_response.invokeStatic(session.clj:52)
	at ring.middleware.session$bare_session_response.invoke(session.clj:43)
	at ring.middleware.session$session_response.invokeStatic(session.clj:74)
	at ring.middleware.session$session_response.invoke(session.clj:66)
	at ring.middleware.session$wrap_session$fn__17005.invoke(session.clj:109)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__17051.invoke(keyword_params.clj:53)
	at ring.middleware.nested_params$wrap_nested_params$fn__17109.invoke(nested_params.clj:89)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__17407.invoke(multipart_params.clj:171)
	at ring.middleware.params$wrap_params$fn__17434.invoke(params.clj:75)
	at ring.middleware.cookies$wrap_cookies$fn__16884.invoke(cookies.clj:214)
	at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__17622.invoke(absolute_redirects.clj:47)
	at ring.middleware.resource$wrap_resource_prefer_resources$fn__17470.invoke(resource.clj:25)
	at ring.middleware.content_type$wrap_content_type$fn__17570.invoke(content_type.clj:34)
	at ring.middleware.default_charset$wrap_default_charset$fn__17594.invoke(default_charset.clj:31)
	at ring.middleware.not_modified$wrap_not_modified$fn__17536.invoke(not_modified.clj:61)
	at ring.middleware.x_headers$wrap_x_header$fn__16537.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__16537.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__16537.invoke(x_headers.clj:22)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at kit.edge.server.undertow$eval16310$fn__16311$fn__16314.invoke(undertow.clj:29)
	at ring.adapter.undertow$undertow_handler$fn$reify__16251.handleRequest(undertow.clj:40)
	at io.undertow.server.session.SessionAttachmentHandler.handleRequest(SessionAttachmentHandler.java:68)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by nikolap** [comment]
Ah you'd need to add readers to the cookie store implementation for that. We don't provide that by default because people may choose to use different time libraries, but I get why it's problematic... any thoughts @yogthos . Here's a sample snippet from a project I'm using. Of course you can replace tick with your choice of date-time library or just native Java.

```clojure
(defn wrap-base
  [{:keys [cookie-opts]}]
  (let [{:keys [cookie-secret cookie-name cookie-default-max-age]} cookie-opts
        cookie-store (session.cookie/cookie-store {:key     (.getBytes ^String cookie-secret)
                                                   :readers {'inst                 (fn [x]
                                                                                     (some-> x (tick/parse) (tick/inst)))
                                                             'time/zoned-date-time #'tick/zoned-date-time}})]
    (fn [handler]
      (cond-> handler
              true (session/wrap-session {:store        cookie-store
                                          :cookie-name  cookie-name
                                          :cookie-attrs {:max-age cookie-default-max-age}})
              true (cookies/wrap-cookies)))))
```

**Comment by nikolap** [comment]
Another option now that I think about it is to use Java's new date/time APIs instead... maybe that would be a sane default

**Comment by yogthos** [comment]
We could add Java default date/time API for cookies, but does seem like a fairly specific use case. It would definitely be good to add this in documentation though.

**Comment by jpe90** [comment]
@nikolap thanks a bunch! I was able to get it working with that info and example.

I'll leave this open since you guys are deciding on adding a default or just noting this in docs, but feel free to close it whenever.

**Comment by yogthos** [comment]
Added an example [under cookie session](https://github.com/kit-clj/kit-clj.github.io/blob/master/resources/md/sessions.md#cookie-encoding) documentation.
